[package]
name = "largefileshare"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3", features = ["multipart"] }
tokio = { version = "1.44.2", features = ["full"] }
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
log = "0.4.27"
